services:
  db:
    image: postgres:16
    container_name: postgres-db
    hostname: postgres-db
    environment:
      POSTGRES_PASSWORD: 
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build: .
    container_name: shopbot-api
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:urpassword@postgres-db:5432/postgres
      - GEMINI_API_KEY=
    restart: on-failure

volumes:
  postgres_data:
